### ISSUE TITLE
[dcc32 Error] JPL.Console.pas(553): E2003 Undeclared identifier: 'Reserved'

### ISSUE THREAD

**Issue by bagualing** [jackdp/JPLib#1]
I got an error when i compiled JPLib package in Delphi 10.4 (Version 27.0.40680.4203):

[dcc32 Error] JPL.Console.pas(553): E2003 Undeclared identifier: 'Reserved'

> function ConWaitForKeyPressed(VirtualKeyCode: WORD = VK_ANY; Milliseconds: DWORD = INFINITE; SleepInterval: DWORD = 25): Boolean;
var
  ir: TInputRecord;
  dwEvents: DWORD;
  tmEnd: DWORD;
  dwKey: WORD;
begin
  Result := False;
  tmEnd := 0;
> 
> ConUpdateStandardHandles;
  if ConStdInput = INVALID_HANDLE_VALUE then Exit;
  if (Milliseconds <> INFINITE) and (Milliseconds > 0) then tmEnd := GetTickCount + Milliseconds;
> 
>  // FPC: initialize
  ir.Reserved := 0;   //<--- **this line report error**.
  dwEvents := 0;

**Comment by bagualing** [comment]
I've almost found the cause of the problem: 

In Winapi.Windows.pas file (Delphi 10.4), There is no longer a ‘Reserved’ field in the _INPUT_RECORD record body.  

>   _INPUT_RECORD = record
    EventType: Word;
    Event: Record case Integer of
      0: (KeyEvent: TKeyEventRecord);
      1: (MouseEvent: TMouseEventRecord);
      2: (WindowBufferSizeEvent: TWindowBufferSizeRecord);
      3: (MenuEvent: TMenuEventRecord);
      4: (FocusEvent: TFocusEventRecord);
    end;
  end;

**Comment by jackdp** [comment]
It seems that EMBT has changed the definition of the TInputRecord in Delphi Sydney.

Fixed.
Thanks for the information.
