### ISSUE TITLE
breakes lazarus compilation

### ISSUE THREAD

**Issue by the-Arioch** [jackdp/JPLib#2]
FPC 3.2.x, Lax 2.0.x or 2.2x on Windows using fpcupdeluxe, both x96 and x64

Reason is Sparta.Generics that conflicts with FPC 3.2. RTL, which already has generics.

This dependency better be removed from `jplib.lpk`

**Comment by the-Arioch** [comment]
[0001-Sparta.Generics-conflicts-with-FPC-3.2.x-makes-Lazar.zip](https://github.com/jackdp/JPLib/files/7832470/0001-Sparta.Generics-conflicts-with-FPC-3.2.x-makes-Lazar.zip)

**Comment by jackdp** [comment]
Thank you.
Dependency on the SPARTA_GENERICS package has been removed.

**Comment by ClubACNews** [comment]
In the release 4.0.0 and 4.2.0, of Lazarus the sparta_generics package is still asked for JPLib installation.
